type Props = {
  className?: string;
  /** "full" for heroes, "simple" for accents. */
  variant?: "full" | "simple";
  /** Render as <img> (needed where the DOM is rasterised, e.g. the story card export). */
  asImage?: boolean;
};

/**
 * Gold line mandala. The geometry is generated by scripts/build-motifs.mjs into
 * /public/motifs and referenced with <use>, so hundreds of decorative nodes stay
 * out of the DOM, the file is cached once, and the colour follows `currentColor`
 * (set it with a text-* class). Decorative: hidden from assistive tech.
 */
export function Mandala({ className = "", variant = "full", asImage = false }: Props) {
  if (asImage) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img src={`/motifs/mandala-${variant}-gold.svg`} alt="" aria-hidden="true" draggable={false} decoding="async" className={className} />
    );
  }
  return (
    <svg viewBox="-250 -250 500 500" aria-hidden="true" focusable="false" className={className}>
      <use href={`/motifs/mandala-${variant}-gold.svg#m`} />
    </svg>
  );
}
